### PR TITLE
Hardcode 4k width and height for ms framebuffer

### PR DESCRIPTION
**Pull request by chrisplatorres**
This PR fixes the right half-eye bug introduced by https://github.com/exokitxr/exokit/commit/b7c81af7d2938d4c8d8f00483d6690acd9ea751a .

### CODE REVIEW

File: deps/exokit-bindings/windowsystem/src/windowsystem.cc [hunk 1]
```diff
@@ -332,8 +332,8 @@ constexpr GLint MAX_TEXTURE_SIZE = 4096;
 bool CreateRenderTarget(WebGLRenderingContext *gl, int width, int height, GLuint sharedColorTex, GLuint sharedDepthStencilTex, GLuint sharedMsColorTex, GLuint sharedMsDepthStencilTex, GLuint *pfbo, GLuint *pcolorTex, GLuint *pdepthStencilTex, GLuint *pmsFbo, GLuint *pmsColorTex, GLuint *pmsDepthStencilTex) {
   const int samples = 4;
 
-  int msWidth, msHeight;
-  windowsystem::GetScreenSize(&msWidth, &msHeight);
+  int msWidth=4096, msHeight=4096;
```
Comment (modulesio) [inline deps/exokit-bindings/windowsystem/src/windowsystem.cc]: Can we use the constant [here](https://github.com/exokitxr/exokit/pull/1036/files#diff-9072aaf78a49fe573d7263fd2ac67503R331) instead?

Comment (chrisplatorres) [reply deps/exokit-bindings/windowsystem/src/windowsystem.cc]: changed in 7bff6b87

**Comment by modulesio** [comment]
The build is broken in this PR:

```
../deps/exokit-bindings/windowsystem/src/windowsystem.cc:335:32: error: 'msWidth' was not declared in this scope
   windowsystem::GetScreenSize(&msWidth, &msHeight);
                                ^~~~~~~
../deps/exokit-bindings/windowsystem/src/windowsystem.cc:335:42: error: 'msHeight' was not declared in this scope
   windowsystem::GetScreenSize(&msWidth, &msHeight);
```

**Comment by modulesio** [comment]
This is known to break some desktop setups. However, moving to [`user-parallel`](https://github.com/exokitxr/exokit/pull/760) should fix this as the blitting model is completely different and resizeable.
